### PR TITLE
Project restaurant-kitchen-service

### PR DESCRIPTION
**Pull request by Yevheniia-Ilchenko**

### CODE REVIEW

**Comment by Evheniia96** [comment]
1.Login page 
image
2. Logout page
image

**Comment by Evheniia96** [comment]
3. Home page 
image
4. All cooks page
image
5. Create cook page(form)
image
6. Cook detail page 
image
7. Update year of experience page 
image
8. Delete cook page 
image

**Comment by Evheniia96** [comment]
3. Home page 
image

**Comment by Evheniia96** [comment]
4. All cook page 
image

**Comment by Evheniia96** [comment]
6. Create cook page 
image
7. Update cook year of experience 
image
8.Delete cook
image

**Comment by Evheniia96** [comment]
9. All dishes page 
image

**Comment by Evheniia96** [comment]
10. Create dish page 
image
image
image

**Comment by Evheniia96** [comment]
11.Dish detail page 
image

**Comment by Evheniia96** [comment]
12. Update dish page 
image
image

**Comment by Yevheniia-Ilchenko** [comment]
New features implemented:
-You can turn off the "Remember me" button if dont want to stay logged in after leaving the website.
-"Sing-up" button added to the Login page.
-"I agree the Terms and Conditions" check-box added to the Login page 

DB structure:
DB

1. Login page 
Screenshot_1
2.Loggout page 
Screenshot_3

**Comment by Yevheniia-Ilchenko** [comment]
3. Home page 
Screenshot_2
Screenshot_4

**Comment by Yevheniia-Ilchenko** [comment]
4. All Cook page:
Screenshot_5
5. Create Cook page (Form):
Screenshot_6
Screenshot_7

6. Cook detail page:
Screenshot_8
7. Cook delete page:
Screenshot_9
8. Cook update year of experience page:
Screenshot_10

**Comment by Yevheniia-Ilchenko** [comment]
9.All Dishes page:
Screenshot_12
10. Create dishes page:
Screenshot_13
Screenshot_14
11. Dish detail page:

Screenshot_15
12. Update dish:
Screenshot_17
Screenshot_18


13. Delete dish:

Screenshot_19

**Comment by Yevheniia-Ilchenko** [comment]
14. All Dith type page :
Screenshot_111
15. Create dish type page :
Screenshot_112
16. Update dish type page :
Screenshot_113
17. Delete dish type page:
Screenshot_115

**Pull request merged**
